Switch back to the previous fedora version being used.
```
Traceback (most recent call last):
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/minion.py", line 1934, in _thread_return
    return_data = minion_instance._execute_job_function(
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/minion.py", line 1893, in _execute_job_function
    return_data = self.executors[fname](opts, data, func, args, kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/modules/virt.py", line 5117, in stop
    ret = _get_domain(conn, name).destroy() == 0
  File "/usr/lib64/python3.10/site-packages/libvirt.py", line 1431, in destroy
    raise libvirtError('virDomainDestroy() failed')
libvirt.libvirtError: Requested operation is not valid: domain is not running
```

```
Traceback (most recent call last):
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/minion.py", line 1934, in _thread_return
    return_data = minion_instance._execute_job_function(
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/minion.py", line 1893, in _execute_job_function
    return_data = self.executors[fname](opts, data, func, args, kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/vampas/projects/Salt
Stack/salt/hotfix/ghcr/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/vampas/projects/SaltStack/salt/hotfix/ghcr/salt/modules/virt.py", line 5090, in start
    ret = _get_domain(conn, name).create() == 0
  File "/usr/lib64/python3.10/site-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: unable to open '/sys/fs/cgroup/machine/qemu-1-core-vm.libvirt-qemu/': No such file or directory
```

Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>